site_name: LinuxCabin
site_description: 为中国用户打造的 Linux 手册 | A Linux handbook especially designed for Chinese users.
site_url: https://hb.linuxcabin.top
repo_name: LinuxCabin/linux-handbook
repo_url: https://codeberg.org/LinuxCabin/linux-handbook
edit_uri: edit/main/docs/

validation:
  nav:
    omitted_files: info

strict: true

theme:
  name: material
  custom_dir: overrides
  language: zh
  palette:
    - scheme: default
      primary: teal
      accent: green
      toggle:
        icon: material/brightness-7
        name: 夜间模式
    - scheme: slate
      primary: black
      accent: teal
      toggle:
        icon: material/brightness-4
        name: 日间模式
  icon:
    logo: material/book-open-page-variant
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye
  features:
    - navigation.footer
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.indexes
    - toc.integrate
    - search.suggest
    - search.highlight
    - search.share
    - content.action.edit
    - content.action.view
    - content.code.copy
    - content.tooltips
    - content.footnote.tooltips
    - announce.dismiss

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.magiclink
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist
  - pymdownx.emoji
  - attr_list
  - tables
  - footnotes
  - md_in_html
  - toc:
      permalink: true

extra_javascript:
  - assets/js/wiki_hover.js
extra_css:
  - assets/css/tippy.css

plugins:
  - search:
      lang: zh
      separator: '[\s\-，。]+'
  - git-revision-date-localized:
      type: datetime
      locale: zh
      fallback_to_build_date: true
#  - git-committers:
#      repository: LinuxCabin/linux-handbook
#      branch: main
#      token: !ENV DEPLOY_KEY
  - minify:
      minify_html: true
      minify_css: true
      minify_js: true

copyright: |
  Licensed under <a href="https://creativecommons.org/licenses/by-nc-nd/4.0/">Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International</a><img src="https://mirrors.creativecommons.org/presskit/icons/cc.svg" alt="" style="max-width: 1em;max-height:1em;margin-left: .2em;"><img src="https://mirrors.creativecommons.org/presskit/icons/by.svg" alt="" style="max-width: 1em;max-height:1em;margin-left: .2em;"><img src="https://mirrors.creativecommons.org/presskit/icons/nc.svg" alt="" style="max-width: 1em;max-height:1em;margin-left: .2em;"><img src="https://mirrors.creativecommons.org/presskit/icons/nd.svg" alt="" style="max-width: 1em;max-height:1em;margin-left: .2em;">

nav:
  - 主页: index.md
  - 开始:
    - getting-started/purpose.md
    - getting-started/before-installing.md
    - getting-started/install.md
    - getting-started/post-installation.md
    - 设备支持:
      - getting-started/devices/drivers.md
      - getting-started/devices/others.md
    - getting-started/input-method.md
    - getting-started/applications.md
    - getting-started/common-command.md
    - getting-started/network.md
  - 概念:
    - Linux基础:
      - concepts/linux/free_software.md
      - concepts/linux/distro.md
      - concepts/linux/mirrors.md
      - concepts/linux/shell.md
      - concepts/linux/rolling_update.md
    - 操作系统:
      - concepts/operating_system/bios.md
      - concepts/operating_system/secure_boot.md
      - concepts/operating_system/boot_loader.md
      - concepts/operating_system/disk_partition_table.md
      - concepts/operating_system/partition.md
      - concepts/operating_system/file_system.md
      - concepts/operating_system/mounting.md
    - 包管理:
      - concepts/package_managers/apt.md
      - concepts/package_managers/dnf.md
      - concepts/package_managers/pacman.md
      - concepts/package_managers/flatpak.md
      - concepts/package_managers/appimage.md
    - 文件系统:
      - concepts/file_system/lvm.md
      - concepts/file_system/btrfs.md
    - 桌面:
      - concepts/desktop/de.md
      - concepts/desktop/tiling_desktop.md
      - concepts/desktop/wm.md
      - concepts/desktop/desktop_shell.md
      - concepts/desktop/dotfiles.md
  - 发行版:
    - distros/distro.md
    - Debian系:
      - distros/debian/graph.md
      - distros/debian/debian.md
      - distros/debian/ubuntu.md
      - distros/debian/linuxmint.md
      - distros/debian/deepin.md
    - 红帽系:
      - distros/rhel/graph.md
      - distros/rhel/fedora.md
      - distros/rhel/rhel.md
      - distros/rhel/rocky.md
      - distros/rhel/almalinux.md
    - Arch系:
      - distros/arch/archlinux.md
      - distros/arch/artixlinux.md
      - distros/arch/cachy.md
    - distros/nixos.md
    - distros/gentoo.md
  - 桌面:
    - 首页: desktop/desktop.md
    - 桌面环境:
      - desktop/de/kde.md
      - desktop/de/gnome.md
    - 窗口管理器:
      - desktop/wm/hyprland.md
      - desktop/wm/niri.md
      - desktop/wm/i3.md
      - desktop/wm/sway.md
  - 兼容性:
    - Win & Linux:
      - compatibility/windows/wine.md
      - compatibility/windows/steam.md
    - 跨发行版:
      - compatibility/inter-distros/distrobox.md
  - 应用与工具:
    - applications/emacs.md
    - applications/vim.md
    - applications/zsh.md
    - applications/fish.md
    - applications/ssh.md
    - applications/git.md
    - applications/openclaw.md
    - 开发相关:
      - applications/programming/cpp.md
      - applications/programming/python.md
      - applications/programming/miniconda.md
      - applications/programming/vscode.md
  #- 进阶:
  - 关于: about.md
