site_name: LinuxCabin
site_description: A Linux handbook especially designed for Chinese users.
repo_name: LinuxCabin/linux-handbook
repo_url: https://github.com/LinuxCabin/linux-handbook
theme:
  name: material
  language: zh
  features:
    - search.suggest
    - search.highlight
    - navigation.footer


markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite

plugins:
  - search


copyright: |
  Licensed under <a href="https://creativecommons.org/licenses/by-nc-nd/4.0/">Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International</a><img src="https://mirrors.creativecommons.org/presskit/icons/cc.svg" alt="" style="max-width: 1em;max-height:1em;margin-left: .2em;"><img src="https://mirrors.creativecommons.org/presskit/icons/by.svg" alt="" style="max-width: 1em;max-height:1em;margin-left: .2em;"><img src="https://mirrors.creativecommons.org/presskit/icons/nc.svg" alt="" style="max-width: 1em;max-height:1em;margin-left: .2em;"><img src="https://mirrors.creativecommons.org/presskit/icons/nd.svg" alt="" style="max-width: 1em;max-height:1em;margin-left: .2em;">

nav:
  - index.md
  - 开始:
    - getting-started/purpose.md
    - getting-started/before-installing.md
    - getting-started/install.md
    - getting-started/post-installation.md
  - 概念:
    - Linux基础:
      - concepts/linux/free_software.md
      - concepts/linux/distro.md
      - concepts/linux/lvm.md
      - concepts/linux/de.md
      - concepts/linux/wm.md
    - 操作系统:
      - concepts/operating_system/bios.md
      - concepts/operating_system/disk_partition_table.md
      - concepts/operating_system/partition.md
      - concepts/operating_system/file_system.md
  - 发行版:
    - Debian系:
      - distros/debian/ubuntu.md
      - distros/debian/linuxmint.md
    - 红帽系:
      - distros/rhel/fedora.md
      - distros/rhel/rhel.md
      - distros/rhel/rocky.md
      - distros/rhel/almalinux.md
    - Arch系:
      - distros/arch/archlinux.md
      - distros/arch/artixlinux.md
      - distros/arch/cachy.md

  - 关于: about.md
