
# Note: This workflow is specially optimized for building the site in Mainland China.

name: Deploy MkDocs to Another Repository

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - 'overrides/**'
      - '.forgejo/workflows/mkdocs-deploy.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - 'overrides/**'
      - '.forgejo/workflows/mkdocs-deploy.yml'
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: build-env
    # Using nikolaik/python-nodejs:python3.14-nodejs26 to avoid the setup conflict between Python and Node.js
    steps:
      - name: Checkout source code
        uses: https://gitea.cn/actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install MkDocs dependencies
        run: |
          python -m pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
          
          python -m pip install --upgrade pip
          
          pip install -r requirements.txt

      - name: Build MkDocs site
        run: mkdocs build --strict

      - name: Deploy to target repository
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        env:
          DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
        run: |
          cd site
          echo "hb.linuxcabin.top" > CNAME
          git init
          git config user.name "Fangcat_Dev"
          git config user.email "f20091219@outlook.com"
          git add .
          git commit -m "Deploy site $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
          git push --force "https://Fangcat_Dev:${DEPLOY_TOKEN}@codeberg.org/LinuxCabin/handbook-site.git" HEAD:pages